"use client";

import { QueryPortfolioNavigationDataResult } from "@/lib/sanity/sanity.types";
import { cn } from "@workspace/ui/lib/utils";
import Link from "next/link";
import { usePathname } from "next/navigation";

export default function PortfolioNavbar({
  links,
  className,
}: {
  // TODO to use the correct type generated by sanity
  links: { _key: string; href: { slug: string }; name: string }[];
  className?: string;
}) {
  const pathname = usePathname();

  return (
    <nav className={cn("", className)}>
      <ul className="flex gap-7 justify-center">
        {links?.map((link) => {
          return (
            <li key={link._key}>
              <Link
                className={cn(
                  "label text-muted-foreground transition-all delay-200 hover:text-accent-foreground",
                  pathname === link.href.slug && "text-accent-foreground",
                )}
                href={link.href?.slug}
              >
                {link.name}
              </Link>
            </li>
          );
        })}
      </ul>
    </nav>
  );
}
